[package]
name = "graphite_render"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.12"
url = "1.7.2"
serde = "1.0.89"
serde_derive = "1.0.89"
chrono = { version = "0.4.6", features = ["serde"] }
itertools = "0.8.0"
